repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/pocc/pre-commit-hooks
    rev: master
    hooks:
    -    id: clang-format
         args: [-i, -style=file]
