version: "3"
services:
  snake:
    image: bsergean/ws:build
    entrypoint: ws snake --port 8765 --host 0.0.0.0 --redis_hosts redis1
    ports:
      - "8765:8765"
    networks:
      - ws-net
    depends_on:
      - redis1

  ws:
    security_opt:
    - seccomp:unconfined
    cap_add:
    - SYS_PTRACE
    stdin_open: true
    tty: true
    image: bsergean/ws:build
    entrypoint: bash
    networks:
      - ws-net
    depends_on:
      - redis1

  redis1:
    image: redis:alpine
    networks:
      - ws-net

networks:
  ws-net:
