# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/bsergeant/src/foss/ixwebsocket/ws

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/bsergeant/src/foss/ixwebsocket

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CMake.app/Contents/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/Applications/CMake.app/Contents/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bsergeant/src/foss/ixwebsocket/CMakeFiles /Users/bsergeant/src/foss/ixwebsocket/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bsergeant/src/foss/ixwebsocket/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ws

# Build rule for target.
ws: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ws
.PHONY : ws

# fast build rule for target.
ws/fast:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/build
.PHONY : ws/fast

IXRedisClient.o: IXRedisClient.cpp.o

.PHONY : IXRedisClient.o

# target to build an object file
IXRedisClient.cpp.o:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/IXRedisClient.cpp.o
.PHONY : IXRedisClient.cpp.o

IXRedisClient.i: IXRedisClient.cpp.i

.PHONY : IXRedisClient.i

# target to preprocess a source file
IXRedisClient.cpp.i:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/IXRedisClient.cpp.i
.PHONY : IXRedisClient.cpp.i

IXRedisClient.s: IXRedisClient.cpp.s

.PHONY : IXRedisClient.s

# target to generate assembly for a file
IXRedisClient.cpp.s:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/IXRedisClient.cpp.s
.PHONY : IXRedisClient.cpp.s

IXSentryClient.o: IXSentryClient.cpp.o

.PHONY : IXSentryClient.o

# target to build an object file
IXSentryClient.cpp.o:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/IXSentryClient.cpp.o
.PHONY : IXSentryClient.cpp.o

IXSentryClient.i: IXSentryClient.cpp.i

.PHONY : IXSentryClient.i

# target to preprocess a source file
IXSentryClient.cpp.i:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/IXSentryClient.cpp.i
.PHONY : IXSentryClient.cpp.i

IXSentryClient.s: IXSentryClient.cpp.s

.PHONY : IXSentryClient.s

# target to generate assembly for a file
IXSentryClient.cpp.s:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/IXSentryClient.cpp.s
.PHONY : IXSentryClient.cpp.s

ixcobra/IXCobraConnection.o: ixcobra/IXCobraConnection.cpp.o

.PHONY : ixcobra/IXCobraConnection.o

# target to build an object file
ixcobra/IXCobraConnection.cpp.o:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ixcobra/IXCobraConnection.cpp.o
.PHONY : ixcobra/IXCobraConnection.cpp.o

ixcobra/IXCobraConnection.i: ixcobra/IXCobraConnection.cpp.i

.PHONY : ixcobra/IXCobraConnection.i

# target to preprocess a source file
ixcobra/IXCobraConnection.cpp.i:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ixcobra/IXCobraConnection.cpp.i
.PHONY : ixcobra/IXCobraConnection.cpp.i

ixcobra/IXCobraConnection.s: ixcobra/IXCobraConnection.cpp.s

.PHONY : ixcobra/IXCobraConnection.s

# target to generate assembly for a file
ixcobra/IXCobraConnection.cpp.s:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ixcobra/IXCobraConnection.cpp.s
.PHONY : ixcobra/IXCobraConnection.cpp.s

ixcobra/IXCobraMetricsPublisher.o: ixcobra/IXCobraMetricsPublisher.cpp.o

.PHONY : ixcobra/IXCobraMetricsPublisher.o

# target to build an object file
ixcobra/IXCobraMetricsPublisher.cpp.o:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ixcobra/IXCobraMetricsPublisher.cpp.o
.PHONY : ixcobra/IXCobraMetricsPublisher.cpp.o

ixcobra/IXCobraMetricsPublisher.i: ixcobra/IXCobraMetricsPublisher.cpp.i

.PHONY : ixcobra/IXCobraMetricsPublisher.i

# target to preprocess a source file
ixcobra/IXCobraMetricsPublisher.cpp.i:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ixcobra/IXCobraMetricsPublisher.cpp.i
.PHONY : ixcobra/IXCobraMetricsPublisher.cpp.i

ixcobra/IXCobraMetricsPublisher.s: ixcobra/IXCobraMetricsPublisher.cpp.s

.PHONY : ixcobra/IXCobraMetricsPublisher.s

# target to generate assembly for a file
ixcobra/IXCobraMetricsPublisher.cpp.s:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ixcobra/IXCobraMetricsPublisher.cpp.s
.PHONY : ixcobra/IXCobraMetricsPublisher.cpp.s

ixcobra/IXCobraMetricsThreadedPublisher.o: ixcobra/IXCobraMetricsThreadedPublisher.cpp.o

.PHONY : ixcobra/IXCobraMetricsThreadedPublisher.o

# target to build an object file
ixcobra/IXCobraMetricsThreadedPublisher.cpp.o:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ixcobra/IXCobraMetricsThreadedPublisher.cpp.o
.PHONY : ixcobra/IXCobraMetricsThreadedPublisher.cpp.o

ixcobra/IXCobraMetricsThreadedPublisher.i: ixcobra/IXCobraMetricsThreadedPublisher.cpp.i

.PHONY : ixcobra/IXCobraMetricsThreadedPublisher.i

# target to preprocess a source file
ixcobra/IXCobraMetricsThreadedPublisher.cpp.i:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ixcobra/IXCobraMetricsThreadedPublisher.cpp.i
.PHONY : ixcobra/IXCobraMetricsThreadedPublisher.cpp.i

ixcobra/IXCobraMetricsThreadedPublisher.s: ixcobra/IXCobraMetricsThreadedPublisher.cpp.s

.PHONY : ixcobra/IXCobraMetricsThreadedPublisher.s

# target to generate assembly for a file
ixcobra/IXCobraMetricsThreadedPublisher.cpp.s:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ixcobra/IXCobraMetricsThreadedPublisher.cpp.s
.PHONY : ixcobra/IXCobraMetricsThreadedPublisher.cpp.s

ixcore/utils/IXCoreLogger.o: ixcore/utils/IXCoreLogger.cpp.o

.PHONY : ixcore/utils/IXCoreLogger.o

# target to build an object file
ixcore/utils/IXCoreLogger.cpp.o:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ixcore/utils/IXCoreLogger.cpp.o
.PHONY : ixcore/utils/IXCoreLogger.cpp.o

ixcore/utils/IXCoreLogger.i: ixcore/utils/IXCoreLogger.cpp.i

.PHONY : ixcore/utils/IXCoreLogger.i

# target to preprocess a source file
ixcore/utils/IXCoreLogger.cpp.i:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ixcore/utils/IXCoreLogger.cpp.i
.PHONY : ixcore/utils/IXCoreLogger.cpp.i

ixcore/utils/IXCoreLogger.s: ixcore/utils/IXCoreLogger.cpp.s

.PHONY : ixcore/utils/IXCoreLogger.s

# target to generate assembly for a file
ixcore/utils/IXCoreLogger.cpp.s:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ixcore/utils/IXCoreLogger.cpp.s
.PHONY : ixcore/utils/IXCoreLogger.cpp.s

ixcrypto/IXBase64.o: ixcrypto/IXBase64.cpp.o

.PHONY : ixcrypto/IXBase64.o

# target to build an object file
ixcrypto/IXBase64.cpp.o:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ixcrypto/IXBase64.cpp.o
.PHONY : ixcrypto/IXBase64.cpp.o

ixcrypto/IXBase64.i: ixcrypto/IXBase64.cpp.i

.PHONY : ixcrypto/IXBase64.i

# target to preprocess a source file
ixcrypto/IXBase64.cpp.i:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ixcrypto/IXBase64.cpp.i
.PHONY : ixcrypto/IXBase64.cpp.i

ixcrypto/IXBase64.s: ixcrypto/IXBase64.cpp.s

.PHONY : ixcrypto/IXBase64.s

# target to generate assembly for a file
ixcrypto/IXBase64.cpp.s:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ixcrypto/IXBase64.cpp.s
.PHONY : ixcrypto/IXBase64.cpp.s

ixcrypto/IXHMac.o: ixcrypto/IXHMac.cpp.o

.PHONY : ixcrypto/IXHMac.o

# target to build an object file
ixcrypto/IXHMac.cpp.o:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ixcrypto/IXHMac.cpp.o
.PHONY : ixcrypto/IXHMac.cpp.o

ixcrypto/IXHMac.i: ixcrypto/IXHMac.cpp.i

.PHONY : ixcrypto/IXHMac.i

# target to preprocess a source file
ixcrypto/IXHMac.cpp.i:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ixcrypto/IXHMac.cpp.i
.PHONY : ixcrypto/IXHMac.cpp.i

ixcrypto/IXHMac.s: ixcrypto/IXHMac.cpp.s

.PHONY : ixcrypto/IXHMac.s

# target to generate assembly for a file
ixcrypto/IXHMac.cpp.s:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ixcrypto/IXHMac.cpp.s
.PHONY : ixcrypto/IXHMac.cpp.s

ixcrypto/IXHash.o: ixcrypto/IXHash.cpp.o

.PHONY : ixcrypto/IXHash.o

# target to build an object file
ixcrypto/IXHash.cpp.o:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ixcrypto/IXHash.cpp.o
.PHONY : ixcrypto/IXHash.cpp.o

ixcrypto/IXHash.i: ixcrypto/IXHash.cpp.i

.PHONY : ixcrypto/IXHash.i

# target to preprocess a source file
ixcrypto/IXHash.cpp.i:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ixcrypto/IXHash.cpp.i
.PHONY : ixcrypto/IXHash.cpp.i

ixcrypto/IXHash.s: ixcrypto/IXHash.cpp.s

.PHONY : ixcrypto/IXHash.s

# target to generate assembly for a file
ixcrypto/IXHash.cpp.s:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ixcrypto/IXHash.cpp.s
.PHONY : ixcrypto/IXHash.cpp.s

ixcrypto/IXUuid.o: ixcrypto/IXUuid.cpp.o

.PHONY : ixcrypto/IXUuid.o

# target to build an object file
ixcrypto/IXUuid.cpp.o:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ixcrypto/IXUuid.cpp.o
.PHONY : ixcrypto/IXUuid.cpp.o

ixcrypto/IXUuid.i: ixcrypto/IXUuid.cpp.i

.PHONY : ixcrypto/IXUuid.i

# target to preprocess a source file
ixcrypto/IXUuid.cpp.i:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ixcrypto/IXUuid.cpp.i
.PHONY : ixcrypto/IXUuid.cpp.i

ixcrypto/IXUuid.s: ixcrypto/IXUuid.cpp.s

.PHONY : ixcrypto/IXUuid.s

# target to generate assembly for a file
ixcrypto/IXUuid.cpp.s:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ixcrypto/IXUuid.cpp.s
.PHONY : ixcrypto/IXUuid.cpp.s

snake/IXAppConfig.o: snake/IXAppConfig.cpp.o

.PHONY : snake/IXAppConfig.o

# target to build an object file
snake/IXAppConfig.cpp.o:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/snake/IXAppConfig.cpp.o
.PHONY : snake/IXAppConfig.cpp.o

snake/IXAppConfig.i: snake/IXAppConfig.cpp.i

.PHONY : snake/IXAppConfig.i

# target to preprocess a source file
snake/IXAppConfig.cpp.i:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/snake/IXAppConfig.cpp.i
.PHONY : snake/IXAppConfig.cpp.i

snake/IXAppConfig.s: snake/IXAppConfig.cpp.s

.PHONY : snake/IXAppConfig.s

# target to generate assembly for a file
snake/IXAppConfig.cpp.s:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/snake/IXAppConfig.cpp.s
.PHONY : snake/IXAppConfig.cpp.s

snake/IXSnakeProtocol.o: snake/IXSnakeProtocol.cpp.o

.PHONY : snake/IXSnakeProtocol.o

# target to build an object file
snake/IXSnakeProtocol.cpp.o:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/snake/IXSnakeProtocol.cpp.o
.PHONY : snake/IXSnakeProtocol.cpp.o

snake/IXSnakeProtocol.i: snake/IXSnakeProtocol.cpp.i

.PHONY : snake/IXSnakeProtocol.i

# target to preprocess a source file
snake/IXSnakeProtocol.cpp.i:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/snake/IXSnakeProtocol.cpp.i
.PHONY : snake/IXSnakeProtocol.cpp.i

snake/IXSnakeProtocol.s: snake/IXSnakeProtocol.cpp.s

.PHONY : snake/IXSnakeProtocol.s

# target to generate assembly for a file
snake/IXSnakeProtocol.cpp.s:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/snake/IXSnakeProtocol.cpp.s
.PHONY : snake/IXSnakeProtocol.cpp.s

snake/IXSnakeServer.o: snake/IXSnakeServer.cpp.o

.PHONY : snake/IXSnakeServer.o

# target to build an object file
snake/IXSnakeServer.cpp.o:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/snake/IXSnakeServer.cpp.o
.PHONY : snake/IXSnakeServer.cpp.o

snake/IXSnakeServer.i: snake/IXSnakeServer.cpp.i

.PHONY : snake/IXSnakeServer.i

# target to preprocess a source file
snake/IXSnakeServer.cpp.i:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/snake/IXSnakeServer.cpp.i
.PHONY : snake/IXSnakeServer.cpp.i

snake/IXSnakeServer.s: snake/IXSnakeServer.cpp.s

.PHONY : snake/IXSnakeServer.s

# target to generate assembly for a file
snake/IXSnakeServer.cpp.s:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/snake/IXSnakeServer.cpp.s
.PHONY : snake/IXSnakeServer.cpp.s

third_party/jsoncpp/jsoncpp.o: third_party/jsoncpp/jsoncpp.cpp.o

.PHONY : third_party/jsoncpp/jsoncpp.o

# target to build an object file
third_party/jsoncpp/jsoncpp.cpp.o:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/third_party/jsoncpp/jsoncpp.cpp.o
.PHONY : third_party/jsoncpp/jsoncpp.cpp.o

third_party/jsoncpp/jsoncpp.i: third_party/jsoncpp/jsoncpp.cpp.i

.PHONY : third_party/jsoncpp/jsoncpp.i

# target to preprocess a source file
third_party/jsoncpp/jsoncpp.cpp.i:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/third_party/jsoncpp/jsoncpp.cpp.i
.PHONY : third_party/jsoncpp/jsoncpp.cpp.i

third_party/jsoncpp/jsoncpp.s: third_party/jsoncpp/jsoncpp.cpp.s

.PHONY : third_party/jsoncpp/jsoncpp.s

# target to generate assembly for a file
third_party/jsoncpp/jsoncpp.cpp.s:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/third_party/jsoncpp/jsoncpp.cpp.s
.PHONY : third_party/jsoncpp/jsoncpp.cpp.s

third_party/msgpack11/msgpack11.o: third_party/msgpack11/msgpack11.cpp.o

.PHONY : third_party/msgpack11/msgpack11.o

# target to build an object file
third_party/msgpack11/msgpack11.cpp.o:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/third_party/msgpack11/msgpack11.cpp.o
.PHONY : third_party/msgpack11/msgpack11.cpp.o

third_party/msgpack11/msgpack11.i: third_party/msgpack11/msgpack11.cpp.i

.PHONY : third_party/msgpack11/msgpack11.i

# target to preprocess a source file
third_party/msgpack11/msgpack11.cpp.i:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/third_party/msgpack11/msgpack11.cpp.i
.PHONY : third_party/msgpack11/msgpack11.cpp.i

third_party/msgpack11/msgpack11.s: third_party/msgpack11/msgpack11.cpp.s

.PHONY : third_party/msgpack11/msgpack11.s

# target to generate assembly for a file
third_party/msgpack11/msgpack11.cpp.s:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/third_party/msgpack11/msgpack11.cpp.s
.PHONY : third_party/msgpack11/msgpack11.cpp.s

third_party/statsd-client-cpp/src/statsd_client.o: third_party/statsd-client-cpp/src/statsd_client.cpp.o

.PHONY : third_party/statsd-client-cpp/src/statsd_client.o

# target to build an object file
third_party/statsd-client-cpp/src/statsd_client.cpp.o:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/third_party/statsd-client-cpp/src/statsd_client.cpp.o
.PHONY : third_party/statsd-client-cpp/src/statsd_client.cpp.o

third_party/statsd-client-cpp/src/statsd_client.i: third_party/statsd-client-cpp/src/statsd_client.cpp.i

.PHONY : third_party/statsd-client-cpp/src/statsd_client.i

# target to preprocess a source file
third_party/statsd-client-cpp/src/statsd_client.cpp.i:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/third_party/statsd-client-cpp/src/statsd_client.cpp.i
.PHONY : third_party/statsd-client-cpp/src/statsd_client.cpp.i

third_party/statsd-client-cpp/src/statsd_client.s: third_party/statsd-client-cpp/src/statsd_client.cpp.s

.PHONY : third_party/statsd-client-cpp/src/statsd_client.s

# target to generate assembly for a file
third_party/statsd-client-cpp/src/statsd_client.cpp.s:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/third_party/statsd-client-cpp/src/statsd_client.cpp.s
.PHONY : third_party/statsd-client-cpp/src/statsd_client.cpp.s

ws.o: ws.cpp.o

.PHONY : ws.o

# target to build an object file
ws.cpp.o:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws.cpp.o
.PHONY : ws.cpp.o

ws.i: ws.cpp.i

.PHONY : ws.i

# target to preprocess a source file
ws.cpp.i:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws.cpp.i
.PHONY : ws.cpp.i

ws.s: ws.cpp.s

.PHONY : ws.s

# target to generate assembly for a file
ws.cpp.s:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws.cpp.s
.PHONY : ws.cpp.s

ws_broadcast_server.o: ws_broadcast_server.cpp.o

.PHONY : ws_broadcast_server.o

# target to build an object file
ws_broadcast_server.cpp.o:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_broadcast_server.cpp.o
.PHONY : ws_broadcast_server.cpp.o

ws_broadcast_server.i: ws_broadcast_server.cpp.i

.PHONY : ws_broadcast_server.i

# target to preprocess a source file
ws_broadcast_server.cpp.i:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_broadcast_server.cpp.i
.PHONY : ws_broadcast_server.cpp.i

ws_broadcast_server.s: ws_broadcast_server.cpp.s

.PHONY : ws_broadcast_server.s

# target to generate assembly for a file
ws_broadcast_server.cpp.s:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_broadcast_server.cpp.s
.PHONY : ws_broadcast_server.cpp.s

ws_chat.o: ws_chat.cpp.o

.PHONY : ws_chat.o

# target to build an object file
ws_chat.cpp.o:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_chat.cpp.o
.PHONY : ws_chat.cpp.o

ws_chat.i: ws_chat.cpp.i

.PHONY : ws_chat.i

# target to preprocess a source file
ws_chat.cpp.i:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_chat.cpp.i
.PHONY : ws_chat.cpp.i

ws_chat.s: ws_chat.cpp.s

.PHONY : ws_chat.s

# target to generate assembly for a file
ws_chat.cpp.s:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_chat.cpp.s
.PHONY : ws_chat.cpp.s

ws_cobra_publish.o: ws_cobra_publish.cpp.o

.PHONY : ws_cobra_publish.o

# target to build an object file
ws_cobra_publish.cpp.o:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_cobra_publish.cpp.o
.PHONY : ws_cobra_publish.cpp.o

ws_cobra_publish.i: ws_cobra_publish.cpp.i

.PHONY : ws_cobra_publish.i

# target to preprocess a source file
ws_cobra_publish.cpp.i:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_cobra_publish.cpp.i
.PHONY : ws_cobra_publish.cpp.i

ws_cobra_publish.s: ws_cobra_publish.cpp.s

.PHONY : ws_cobra_publish.s

# target to generate assembly for a file
ws_cobra_publish.cpp.s:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_cobra_publish.cpp.s
.PHONY : ws_cobra_publish.cpp.s

ws_cobra_subscribe.o: ws_cobra_subscribe.cpp.o

.PHONY : ws_cobra_subscribe.o

# target to build an object file
ws_cobra_subscribe.cpp.o:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_cobra_subscribe.cpp.o
.PHONY : ws_cobra_subscribe.cpp.o

ws_cobra_subscribe.i: ws_cobra_subscribe.cpp.i

.PHONY : ws_cobra_subscribe.i

# target to preprocess a source file
ws_cobra_subscribe.cpp.i:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_cobra_subscribe.cpp.i
.PHONY : ws_cobra_subscribe.cpp.i

ws_cobra_subscribe.s: ws_cobra_subscribe.cpp.s

.PHONY : ws_cobra_subscribe.s

# target to generate assembly for a file
ws_cobra_subscribe.cpp.s:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_cobra_subscribe.cpp.s
.PHONY : ws_cobra_subscribe.cpp.s

ws_cobra_to_sentry.o: ws_cobra_to_sentry.cpp.o

.PHONY : ws_cobra_to_sentry.o

# target to build an object file
ws_cobra_to_sentry.cpp.o:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_cobra_to_sentry.cpp.o
.PHONY : ws_cobra_to_sentry.cpp.o

ws_cobra_to_sentry.i: ws_cobra_to_sentry.cpp.i

.PHONY : ws_cobra_to_sentry.i

# target to preprocess a source file
ws_cobra_to_sentry.cpp.i:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_cobra_to_sentry.cpp.i
.PHONY : ws_cobra_to_sentry.cpp.i

ws_cobra_to_sentry.s: ws_cobra_to_sentry.cpp.s

.PHONY : ws_cobra_to_sentry.s

# target to generate assembly for a file
ws_cobra_to_sentry.cpp.s:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_cobra_to_sentry.cpp.s
.PHONY : ws_cobra_to_sentry.cpp.s

ws_cobra_to_statsd.o: ws_cobra_to_statsd.cpp.o

.PHONY : ws_cobra_to_statsd.o

# target to build an object file
ws_cobra_to_statsd.cpp.o:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_cobra_to_statsd.cpp.o
.PHONY : ws_cobra_to_statsd.cpp.o

ws_cobra_to_statsd.i: ws_cobra_to_statsd.cpp.i

.PHONY : ws_cobra_to_statsd.i

# target to preprocess a source file
ws_cobra_to_statsd.cpp.i:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_cobra_to_statsd.cpp.i
.PHONY : ws_cobra_to_statsd.cpp.i

ws_cobra_to_statsd.s: ws_cobra_to_statsd.cpp.s

.PHONY : ws_cobra_to_statsd.s

# target to generate assembly for a file
ws_cobra_to_statsd.cpp.s:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_cobra_to_statsd.cpp.s
.PHONY : ws_cobra_to_statsd.cpp.s

ws_connect.o: ws_connect.cpp.o

.PHONY : ws_connect.o

# target to build an object file
ws_connect.cpp.o:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_connect.cpp.o
.PHONY : ws_connect.cpp.o

ws_connect.i: ws_connect.cpp.i

.PHONY : ws_connect.i

# target to preprocess a source file
ws_connect.cpp.i:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_connect.cpp.i
.PHONY : ws_connect.cpp.i

ws_connect.s: ws_connect.cpp.s

.PHONY : ws_connect.s

# target to generate assembly for a file
ws_connect.cpp.s:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_connect.cpp.s
.PHONY : ws_connect.cpp.s

ws_echo_server.o: ws_echo_server.cpp.o

.PHONY : ws_echo_server.o

# target to build an object file
ws_echo_server.cpp.o:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_echo_server.cpp.o
.PHONY : ws_echo_server.cpp.o

ws_echo_server.i: ws_echo_server.cpp.i

.PHONY : ws_echo_server.i

# target to preprocess a source file
ws_echo_server.cpp.i:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_echo_server.cpp.i
.PHONY : ws_echo_server.cpp.i

ws_echo_server.s: ws_echo_server.cpp.s

.PHONY : ws_echo_server.s

# target to generate assembly for a file
ws_echo_server.cpp.s:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_echo_server.cpp.s
.PHONY : ws_echo_server.cpp.s

ws_http_client.o: ws_http_client.cpp.o

.PHONY : ws_http_client.o

# target to build an object file
ws_http_client.cpp.o:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_http_client.cpp.o
.PHONY : ws_http_client.cpp.o

ws_http_client.i: ws_http_client.cpp.i

.PHONY : ws_http_client.i

# target to preprocess a source file
ws_http_client.cpp.i:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_http_client.cpp.i
.PHONY : ws_http_client.cpp.i

ws_http_client.s: ws_http_client.cpp.s

.PHONY : ws_http_client.s

# target to generate assembly for a file
ws_http_client.cpp.s:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_http_client.cpp.s
.PHONY : ws_http_client.cpp.s

ws_ping_pong.o: ws_ping_pong.cpp.o

.PHONY : ws_ping_pong.o

# target to build an object file
ws_ping_pong.cpp.o:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_ping_pong.cpp.o
.PHONY : ws_ping_pong.cpp.o

ws_ping_pong.i: ws_ping_pong.cpp.i

.PHONY : ws_ping_pong.i

# target to preprocess a source file
ws_ping_pong.cpp.i:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_ping_pong.cpp.i
.PHONY : ws_ping_pong.cpp.i

ws_ping_pong.s: ws_ping_pong.cpp.s

.PHONY : ws_ping_pong.s

# target to generate assembly for a file
ws_ping_pong.cpp.s:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_ping_pong.cpp.s
.PHONY : ws_ping_pong.cpp.s

ws_receive.o: ws_receive.cpp.o

.PHONY : ws_receive.o

# target to build an object file
ws_receive.cpp.o:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_receive.cpp.o
.PHONY : ws_receive.cpp.o

ws_receive.i: ws_receive.cpp.i

.PHONY : ws_receive.i

# target to preprocess a source file
ws_receive.cpp.i:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_receive.cpp.i
.PHONY : ws_receive.cpp.i

ws_receive.s: ws_receive.cpp.s

.PHONY : ws_receive.s

# target to generate assembly for a file
ws_receive.cpp.s:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_receive.cpp.s
.PHONY : ws_receive.cpp.s

ws_redis_publish.o: ws_redis_publish.cpp.o

.PHONY : ws_redis_publish.o

# target to build an object file
ws_redis_publish.cpp.o:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_redis_publish.cpp.o
.PHONY : ws_redis_publish.cpp.o

ws_redis_publish.i: ws_redis_publish.cpp.i

.PHONY : ws_redis_publish.i

# target to preprocess a source file
ws_redis_publish.cpp.i:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_redis_publish.cpp.i
.PHONY : ws_redis_publish.cpp.i

ws_redis_publish.s: ws_redis_publish.cpp.s

.PHONY : ws_redis_publish.s

# target to generate assembly for a file
ws_redis_publish.cpp.s:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_redis_publish.cpp.s
.PHONY : ws_redis_publish.cpp.s

ws_redis_subscribe.o: ws_redis_subscribe.cpp.o

.PHONY : ws_redis_subscribe.o

# target to build an object file
ws_redis_subscribe.cpp.o:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_redis_subscribe.cpp.o
.PHONY : ws_redis_subscribe.cpp.o

ws_redis_subscribe.i: ws_redis_subscribe.cpp.i

.PHONY : ws_redis_subscribe.i

# target to preprocess a source file
ws_redis_subscribe.cpp.i:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_redis_subscribe.cpp.i
.PHONY : ws_redis_subscribe.cpp.i

ws_redis_subscribe.s: ws_redis_subscribe.cpp.s

.PHONY : ws_redis_subscribe.s

# target to generate assembly for a file
ws_redis_subscribe.cpp.s:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_redis_subscribe.cpp.s
.PHONY : ws_redis_subscribe.cpp.s

ws_send.o: ws_send.cpp.o

.PHONY : ws_send.o

# target to build an object file
ws_send.cpp.o:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_send.cpp.o
.PHONY : ws_send.cpp.o

ws_send.i: ws_send.cpp.i

.PHONY : ws_send.i

# target to preprocess a source file
ws_send.cpp.i:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_send.cpp.i
.PHONY : ws_send.cpp.i

ws_send.s: ws_send.cpp.s

.PHONY : ws_send.s

# target to generate assembly for a file
ws_send.cpp.s:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_send.cpp.s
.PHONY : ws_send.cpp.s

ws_snake.o: ws_snake.cpp.o

.PHONY : ws_snake.o

# target to build an object file
ws_snake.cpp.o:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_snake.cpp.o
.PHONY : ws_snake.cpp.o

ws_snake.i: ws_snake.cpp.i

.PHONY : ws_snake.i

# target to preprocess a source file
ws_snake.cpp.i:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_snake.cpp.i
.PHONY : ws_snake.cpp.i

ws_snake.s: ws_snake.cpp.s

.PHONY : ws_snake.s

# target to generate assembly for a file
ws_snake.cpp.s:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_snake.cpp.s
.PHONY : ws_snake.cpp.s

ws_transfer.o: ws_transfer.cpp.o

.PHONY : ws_transfer.o

# target to build an object file
ws_transfer.cpp.o:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_transfer.cpp.o
.PHONY : ws_transfer.cpp.o

ws_transfer.i: ws_transfer.cpp.i

.PHONY : ws_transfer.i

# target to preprocess a source file
ws_transfer.cpp.i:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_transfer.cpp.i
.PHONY : ws_transfer.cpp.i

ws_transfer.s: ws_transfer.cpp.s

.PHONY : ws_transfer.s

# target to generate assembly for a file
ws_transfer.cpp.s:
	$(MAKE) -f CMakeFiles/ws.dir/build.make CMakeFiles/ws.dir/ws_transfer.cpp.s
.PHONY : ws_transfer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/local"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... install/strip"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... ws"
	@echo "... IXRedisClient.o"
	@echo "... IXRedisClient.i"
	@echo "... IXRedisClient.s"
	@echo "... IXSentryClient.o"
	@echo "... IXSentryClient.i"
	@echo "... IXSentryClient.s"
	@echo "... ixcobra/IXCobraConnection.o"
	@echo "... ixcobra/IXCobraConnection.i"
	@echo "... ixcobra/IXCobraConnection.s"
	@echo "... ixcobra/IXCobraMetricsPublisher.o"
	@echo "... ixcobra/IXCobraMetricsPublisher.i"
	@echo "... ixcobra/IXCobraMetricsPublisher.s"
	@echo "... ixcobra/IXCobraMetricsThreadedPublisher.o"
	@echo "... ixcobra/IXCobraMetricsThreadedPublisher.i"
	@echo "... ixcobra/IXCobraMetricsThreadedPublisher.s"
	@echo "... ixcore/utils/IXCoreLogger.o"
	@echo "... ixcore/utils/IXCoreLogger.i"
	@echo "... ixcore/utils/IXCoreLogger.s"
	@echo "... ixcrypto/IXBase64.o"
	@echo "... ixcrypto/IXBase64.i"
	@echo "... ixcrypto/IXBase64.s"
	@echo "... ixcrypto/IXHMac.o"
	@echo "... ixcrypto/IXHMac.i"
	@echo "... ixcrypto/IXHMac.s"
	@echo "... ixcrypto/IXHash.o"
	@echo "... ixcrypto/IXHash.i"
	@echo "... ixcrypto/IXHash.s"
	@echo "... ixcrypto/IXUuid.o"
	@echo "... ixcrypto/IXUuid.i"
	@echo "... ixcrypto/IXUuid.s"
	@echo "... snake/IXAppConfig.o"
	@echo "... snake/IXAppConfig.i"
	@echo "... snake/IXAppConfig.s"
	@echo "... snake/IXSnakeProtocol.o"
	@echo "... snake/IXSnakeProtocol.i"
	@echo "... snake/IXSnakeProtocol.s"
	@echo "... snake/IXSnakeServer.o"
	@echo "... snake/IXSnakeServer.i"
	@echo "... snake/IXSnakeServer.s"
	@echo "... third_party/jsoncpp/jsoncpp.o"
	@echo "... third_party/jsoncpp/jsoncpp.i"
	@echo "... third_party/jsoncpp/jsoncpp.s"
	@echo "... third_party/msgpack11/msgpack11.o"
	@echo "... third_party/msgpack11/msgpack11.i"
	@echo "... third_party/msgpack11/msgpack11.s"
	@echo "... third_party/statsd-client-cpp/src/statsd_client.o"
	@echo "... third_party/statsd-client-cpp/src/statsd_client.i"
	@echo "... third_party/statsd-client-cpp/src/statsd_client.s"
	@echo "... ws.o"
	@echo "... ws.i"
	@echo "... ws.s"
	@echo "... ws_broadcast_server.o"
	@echo "... ws_broadcast_server.i"
	@echo "... ws_broadcast_server.s"
	@echo "... ws_chat.o"
	@echo "... ws_chat.i"
	@echo "... ws_chat.s"
	@echo "... ws_cobra_publish.o"
	@echo "... ws_cobra_publish.i"
	@echo "... ws_cobra_publish.s"
	@echo "... ws_cobra_subscribe.o"
	@echo "... ws_cobra_subscribe.i"
	@echo "... ws_cobra_subscribe.s"
	@echo "... ws_cobra_to_sentry.o"
	@echo "... ws_cobra_to_sentry.i"
	@echo "... ws_cobra_to_sentry.s"
	@echo "... ws_cobra_to_statsd.o"
	@echo "... ws_cobra_to_statsd.i"
	@echo "... ws_cobra_to_statsd.s"
	@echo "... ws_connect.o"
	@echo "... ws_connect.i"
	@echo "... ws_connect.s"
	@echo "... ws_echo_server.o"
	@echo "... ws_echo_server.i"
	@echo "... ws_echo_server.s"
	@echo "... ws_http_client.o"
	@echo "... ws_http_client.i"
	@echo "... ws_http_client.s"
	@echo "... ws_ping_pong.o"
	@echo "... ws_ping_pong.i"
	@echo "... ws_ping_pong.s"
	@echo "... ws_receive.o"
	@echo "... ws_receive.i"
	@echo "... ws_receive.s"
	@echo "... ws_redis_publish.o"
	@echo "... ws_redis_publish.i"
	@echo "... ws_redis_publish.s"
	@echo "... ws_redis_subscribe.o"
	@echo "... ws_redis_subscribe.i"
	@echo "... ws_redis_subscribe.s"
	@echo "... ws_send.o"
	@echo "... ws_send.i"
	@echo "... ws_send.s"
	@echo "... ws_snake.o"
	@echo "... ws_snake.i"
	@echo "... ws_snake.s"
	@echo "... ws_transfer.o"
	@echo "... ws_transfer.i"
	@echo "... ws_transfer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

