# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ivddorrka/proxy_ghs/IXWebSocket

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ivddorrka/proxy_ghs/IXWebSocket

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ivddorrka/proxy_ghs/IXWebSocket/CMakeFiles /home/ivddorrka/proxy_ghs/IXWebSocket/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ivddorrka/proxy_ghs/IXWebSocket/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named demo

# Build rule for target.
demo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 demo
.PHONY : demo

# fast build rule for target.
demo/fast:
	$(MAKE) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/build
.PHONY : demo/fast

#=============================================================================
# Target rules for targets named ixwebsocket

# Build rule for target.
ixwebsocket: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ixwebsocket
.PHONY : ixwebsocket

# fast build rule for target.
ixwebsocket/fast:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/build
.PHONY : ixwebsocket/fast

ixwebsocket/IXBench.o: ixwebsocket/IXBench.cpp.o

.PHONY : ixwebsocket/IXBench.o

# target to build an object file
ixwebsocket/IXBench.cpp.o:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXBench.cpp.o
.PHONY : ixwebsocket/IXBench.cpp.o

ixwebsocket/IXBench.i: ixwebsocket/IXBench.cpp.i

.PHONY : ixwebsocket/IXBench.i

# target to preprocess a source file
ixwebsocket/IXBench.cpp.i:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXBench.cpp.i
.PHONY : ixwebsocket/IXBench.cpp.i

ixwebsocket/IXBench.s: ixwebsocket/IXBench.cpp.s

.PHONY : ixwebsocket/IXBench.s

# target to generate assembly for a file
ixwebsocket/IXBench.cpp.s:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXBench.cpp.s
.PHONY : ixwebsocket/IXBench.cpp.s

ixwebsocket/IXCancellationRequest.o: ixwebsocket/IXCancellationRequest.cpp.o

.PHONY : ixwebsocket/IXCancellationRequest.o

# target to build an object file
ixwebsocket/IXCancellationRequest.cpp.o:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXCancellationRequest.cpp.o
.PHONY : ixwebsocket/IXCancellationRequest.cpp.o

ixwebsocket/IXCancellationRequest.i: ixwebsocket/IXCancellationRequest.cpp.i

.PHONY : ixwebsocket/IXCancellationRequest.i

# target to preprocess a source file
ixwebsocket/IXCancellationRequest.cpp.i:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXCancellationRequest.cpp.i
.PHONY : ixwebsocket/IXCancellationRequest.cpp.i

ixwebsocket/IXCancellationRequest.s: ixwebsocket/IXCancellationRequest.cpp.s

.PHONY : ixwebsocket/IXCancellationRequest.s

# target to generate assembly for a file
ixwebsocket/IXCancellationRequest.cpp.s:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXCancellationRequest.cpp.s
.PHONY : ixwebsocket/IXCancellationRequest.cpp.s

ixwebsocket/IXConnectionState.o: ixwebsocket/IXConnectionState.cpp.o

.PHONY : ixwebsocket/IXConnectionState.o

# target to build an object file
ixwebsocket/IXConnectionState.cpp.o:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXConnectionState.cpp.o
.PHONY : ixwebsocket/IXConnectionState.cpp.o

ixwebsocket/IXConnectionState.i: ixwebsocket/IXConnectionState.cpp.i

.PHONY : ixwebsocket/IXConnectionState.i

# target to preprocess a source file
ixwebsocket/IXConnectionState.cpp.i:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXConnectionState.cpp.i
.PHONY : ixwebsocket/IXConnectionState.cpp.i

ixwebsocket/IXConnectionState.s: ixwebsocket/IXConnectionState.cpp.s

.PHONY : ixwebsocket/IXConnectionState.s

# target to generate assembly for a file
ixwebsocket/IXConnectionState.cpp.s:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXConnectionState.cpp.s
.PHONY : ixwebsocket/IXConnectionState.cpp.s

ixwebsocket/IXDNSLookup.o: ixwebsocket/IXDNSLookup.cpp.o

.PHONY : ixwebsocket/IXDNSLookup.o

# target to build an object file
ixwebsocket/IXDNSLookup.cpp.o:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXDNSLookup.cpp.o
.PHONY : ixwebsocket/IXDNSLookup.cpp.o

ixwebsocket/IXDNSLookup.i: ixwebsocket/IXDNSLookup.cpp.i

.PHONY : ixwebsocket/IXDNSLookup.i

# target to preprocess a source file
ixwebsocket/IXDNSLookup.cpp.i:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXDNSLookup.cpp.i
.PHONY : ixwebsocket/IXDNSLookup.cpp.i

ixwebsocket/IXDNSLookup.s: ixwebsocket/IXDNSLookup.cpp.s

.PHONY : ixwebsocket/IXDNSLookup.s

# target to generate assembly for a file
ixwebsocket/IXDNSLookup.cpp.s:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXDNSLookup.cpp.s
.PHONY : ixwebsocket/IXDNSLookup.cpp.s

ixwebsocket/IXExponentialBackoff.o: ixwebsocket/IXExponentialBackoff.cpp.o

.PHONY : ixwebsocket/IXExponentialBackoff.o

# target to build an object file
ixwebsocket/IXExponentialBackoff.cpp.o:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXExponentialBackoff.cpp.o
.PHONY : ixwebsocket/IXExponentialBackoff.cpp.o

ixwebsocket/IXExponentialBackoff.i: ixwebsocket/IXExponentialBackoff.cpp.i

.PHONY : ixwebsocket/IXExponentialBackoff.i

# target to preprocess a source file
ixwebsocket/IXExponentialBackoff.cpp.i:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXExponentialBackoff.cpp.i
.PHONY : ixwebsocket/IXExponentialBackoff.cpp.i

ixwebsocket/IXExponentialBackoff.s: ixwebsocket/IXExponentialBackoff.cpp.s

.PHONY : ixwebsocket/IXExponentialBackoff.s

# target to generate assembly for a file
ixwebsocket/IXExponentialBackoff.cpp.s:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXExponentialBackoff.cpp.s
.PHONY : ixwebsocket/IXExponentialBackoff.cpp.s

ixwebsocket/IXGetFreePort.o: ixwebsocket/IXGetFreePort.cpp.o

.PHONY : ixwebsocket/IXGetFreePort.o

# target to build an object file
ixwebsocket/IXGetFreePort.cpp.o:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXGetFreePort.cpp.o
.PHONY : ixwebsocket/IXGetFreePort.cpp.o

ixwebsocket/IXGetFreePort.i: ixwebsocket/IXGetFreePort.cpp.i

.PHONY : ixwebsocket/IXGetFreePort.i

# target to preprocess a source file
ixwebsocket/IXGetFreePort.cpp.i:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXGetFreePort.cpp.i
.PHONY : ixwebsocket/IXGetFreePort.cpp.i

ixwebsocket/IXGetFreePort.s: ixwebsocket/IXGetFreePort.cpp.s

.PHONY : ixwebsocket/IXGetFreePort.s

# target to generate assembly for a file
ixwebsocket/IXGetFreePort.cpp.s:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXGetFreePort.cpp.s
.PHONY : ixwebsocket/IXGetFreePort.cpp.s

ixwebsocket/IXGzipCodec.o: ixwebsocket/IXGzipCodec.cpp.o

.PHONY : ixwebsocket/IXGzipCodec.o

# target to build an object file
ixwebsocket/IXGzipCodec.cpp.o:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXGzipCodec.cpp.o
.PHONY : ixwebsocket/IXGzipCodec.cpp.o

ixwebsocket/IXGzipCodec.i: ixwebsocket/IXGzipCodec.cpp.i

.PHONY : ixwebsocket/IXGzipCodec.i

# target to preprocess a source file
ixwebsocket/IXGzipCodec.cpp.i:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXGzipCodec.cpp.i
.PHONY : ixwebsocket/IXGzipCodec.cpp.i

ixwebsocket/IXGzipCodec.s: ixwebsocket/IXGzipCodec.cpp.s

.PHONY : ixwebsocket/IXGzipCodec.s

# target to generate assembly for a file
ixwebsocket/IXGzipCodec.cpp.s:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXGzipCodec.cpp.s
.PHONY : ixwebsocket/IXGzipCodec.cpp.s

ixwebsocket/IXHttp.o: ixwebsocket/IXHttp.cpp.o

.PHONY : ixwebsocket/IXHttp.o

# target to build an object file
ixwebsocket/IXHttp.cpp.o:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXHttp.cpp.o
.PHONY : ixwebsocket/IXHttp.cpp.o

ixwebsocket/IXHttp.i: ixwebsocket/IXHttp.cpp.i

.PHONY : ixwebsocket/IXHttp.i

# target to preprocess a source file
ixwebsocket/IXHttp.cpp.i:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXHttp.cpp.i
.PHONY : ixwebsocket/IXHttp.cpp.i

ixwebsocket/IXHttp.s: ixwebsocket/IXHttp.cpp.s

.PHONY : ixwebsocket/IXHttp.s

# target to generate assembly for a file
ixwebsocket/IXHttp.cpp.s:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXHttp.cpp.s
.PHONY : ixwebsocket/IXHttp.cpp.s

ixwebsocket/IXHttpClient.o: ixwebsocket/IXHttpClient.cpp.o

.PHONY : ixwebsocket/IXHttpClient.o

# target to build an object file
ixwebsocket/IXHttpClient.cpp.o:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXHttpClient.cpp.o
.PHONY : ixwebsocket/IXHttpClient.cpp.o

ixwebsocket/IXHttpClient.i: ixwebsocket/IXHttpClient.cpp.i

.PHONY : ixwebsocket/IXHttpClient.i

# target to preprocess a source file
ixwebsocket/IXHttpClient.cpp.i:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXHttpClient.cpp.i
.PHONY : ixwebsocket/IXHttpClient.cpp.i

ixwebsocket/IXHttpClient.s: ixwebsocket/IXHttpClient.cpp.s

.PHONY : ixwebsocket/IXHttpClient.s

# target to generate assembly for a file
ixwebsocket/IXHttpClient.cpp.s:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXHttpClient.cpp.s
.PHONY : ixwebsocket/IXHttpClient.cpp.s

ixwebsocket/IXHttpServer.o: ixwebsocket/IXHttpServer.cpp.o

.PHONY : ixwebsocket/IXHttpServer.o

# target to build an object file
ixwebsocket/IXHttpServer.cpp.o:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXHttpServer.cpp.o
.PHONY : ixwebsocket/IXHttpServer.cpp.o

ixwebsocket/IXHttpServer.i: ixwebsocket/IXHttpServer.cpp.i

.PHONY : ixwebsocket/IXHttpServer.i

# target to preprocess a source file
ixwebsocket/IXHttpServer.cpp.i:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXHttpServer.cpp.i
.PHONY : ixwebsocket/IXHttpServer.cpp.i

ixwebsocket/IXHttpServer.s: ixwebsocket/IXHttpServer.cpp.s

.PHONY : ixwebsocket/IXHttpServer.s

# target to generate assembly for a file
ixwebsocket/IXHttpServer.cpp.s:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXHttpServer.cpp.s
.PHONY : ixwebsocket/IXHttpServer.cpp.s

ixwebsocket/IXNetSystem.o: ixwebsocket/IXNetSystem.cpp.o

.PHONY : ixwebsocket/IXNetSystem.o

# target to build an object file
ixwebsocket/IXNetSystem.cpp.o:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXNetSystem.cpp.o
.PHONY : ixwebsocket/IXNetSystem.cpp.o

ixwebsocket/IXNetSystem.i: ixwebsocket/IXNetSystem.cpp.i

.PHONY : ixwebsocket/IXNetSystem.i

# target to preprocess a source file
ixwebsocket/IXNetSystem.cpp.i:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXNetSystem.cpp.i
.PHONY : ixwebsocket/IXNetSystem.cpp.i

ixwebsocket/IXNetSystem.s: ixwebsocket/IXNetSystem.cpp.s

.PHONY : ixwebsocket/IXNetSystem.s

# target to generate assembly for a file
ixwebsocket/IXNetSystem.cpp.s:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXNetSystem.cpp.s
.PHONY : ixwebsocket/IXNetSystem.cpp.s

ixwebsocket/IXSelectInterrupt.o: ixwebsocket/IXSelectInterrupt.cpp.o

.PHONY : ixwebsocket/IXSelectInterrupt.o

# target to build an object file
ixwebsocket/IXSelectInterrupt.cpp.o:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXSelectInterrupt.cpp.o
.PHONY : ixwebsocket/IXSelectInterrupt.cpp.o

ixwebsocket/IXSelectInterrupt.i: ixwebsocket/IXSelectInterrupt.cpp.i

.PHONY : ixwebsocket/IXSelectInterrupt.i

# target to preprocess a source file
ixwebsocket/IXSelectInterrupt.cpp.i:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXSelectInterrupt.cpp.i
.PHONY : ixwebsocket/IXSelectInterrupt.cpp.i

ixwebsocket/IXSelectInterrupt.s: ixwebsocket/IXSelectInterrupt.cpp.s

.PHONY : ixwebsocket/IXSelectInterrupt.s

# target to generate assembly for a file
ixwebsocket/IXSelectInterrupt.cpp.s:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXSelectInterrupt.cpp.s
.PHONY : ixwebsocket/IXSelectInterrupt.cpp.s

ixwebsocket/IXSelectInterruptEvent.o: ixwebsocket/IXSelectInterruptEvent.cpp.o

.PHONY : ixwebsocket/IXSelectInterruptEvent.o

# target to build an object file
ixwebsocket/IXSelectInterruptEvent.cpp.o:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXSelectInterruptEvent.cpp.o
.PHONY : ixwebsocket/IXSelectInterruptEvent.cpp.o

ixwebsocket/IXSelectInterruptEvent.i: ixwebsocket/IXSelectInterruptEvent.cpp.i

.PHONY : ixwebsocket/IXSelectInterruptEvent.i

# target to preprocess a source file
ixwebsocket/IXSelectInterruptEvent.cpp.i:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXSelectInterruptEvent.cpp.i
.PHONY : ixwebsocket/IXSelectInterruptEvent.cpp.i

ixwebsocket/IXSelectInterruptEvent.s: ixwebsocket/IXSelectInterruptEvent.cpp.s

.PHONY : ixwebsocket/IXSelectInterruptEvent.s

# target to generate assembly for a file
ixwebsocket/IXSelectInterruptEvent.cpp.s:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXSelectInterruptEvent.cpp.s
.PHONY : ixwebsocket/IXSelectInterruptEvent.cpp.s

ixwebsocket/IXSelectInterruptFactory.o: ixwebsocket/IXSelectInterruptFactory.cpp.o

.PHONY : ixwebsocket/IXSelectInterruptFactory.o

# target to build an object file
ixwebsocket/IXSelectInterruptFactory.cpp.o:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXSelectInterruptFactory.cpp.o
.PHONY : ixwebsocket/IXSelectInterruptFactory.cpp.o

ixwebsocket/IXSelectInterruptFactory.i: ixwebsocket/IXSelectInterruptFactory.cpp.i

.PHONY : ixwebsocket/IXSelectInterruptFactory.i

# target to preprocess a source file
ixwebsocket/IXSelectInterruptFactory.cpp.i:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXSelectInterruptFactory.cpp.i
.PHONY : ixwebsocket/IXSelectInterruptFactory.cpp.i

ixwebsocket/IXSelectInterruptFactory.s: ixwebsocket/IXSelectInterruptFactory.cpp.s

.PHONY : ixwebsocket/IXSelectInterruptFactory.s

# target to generate assembly for a file
ixwebsocket/IXSelectInterruptFactory.cpp.s:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXSelectInterruptFactory.cpp.s
.PHONY : ixwebsocket/IXSelectInterruptFactory.cpp.s

ixwebsocket/IXSelectInterruptPipe.o: ixwebsocket/IXSelectInterruptPipe.cpp.o

.PHONY : ixwebsocket/IXSelectInterruptPipe.o

# target to build an object file
ixwebsocket/IXSelectInterruptPipe.cpp.o:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXSelectInterruptPipe.cpp.o
.PHONY : ixwebsocket/IXSelectInterruptPipe.cpp.o

ixwebsocket/IXSelectInterruptPipe.i: ixwebsocket/IXSelectInterruptPipe.cpp.i

.PHONY : ixwebsocket/IXSelectInterruptPipe.i

# target to preprocess a source file
ixwebsocket/IXSelectInterruptPipe.cpp.i:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXSelectInterruptPipe.cpp.i
.PHONY : ixwebsocket/IXSelectInterruptPipe.cpp.i

ixwebsocket/IXSelectInterruptPipe.s: ixwebsocket/IXSelectInterruptPipe.cpp.s

.PHONY : ixwebsocket/IXSelectInterruptPipe.s

# target to generate assembly for a file
ixwebsocket/IXSelectInterruptPipe.cpp.s:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXSelectInterruptPipe.cpp.s
.PHONY : ixwebsocket/IXSelectInterruptPipe.cpp.s

ixwebsocket/IXSetThreadName.o: ixwebsocket/IXSetThreadName.cpp.o

.PHONY : ixwebsocket/IXSetThreadName.o

# target to build an object file
ixwebsocket/IXSetThreadName.cpp.o:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXSetThreadName.cpp.o
.PHONY : ixwebsocket/IXSetThreadName.cpp.o

ixwebsocket/IXSetThreadName.i: ixwebsocket/IXSetThreadName.cpp.i

.PHONY : ixwebsocket/IXSetThreadName.i

# target to preprocess a source file
ixwebsocket/IXSetThreadName.cpp.i:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXSetThreadName.cpp.i
.PHONY : ixwebsocket/IXSetThreadName.cpp.i

ixwebsocket/IXSetThreadName.s: ixwebsocket/IXSetThreadName.cpp.s

.PHONY : ixwebsocket/IXSetThreadName.s

# target to generate assembly for a file
ixwebsocket/IXSetThreadName.cpp.s:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXSetThreadName.cpp.s
.PHONY : ixwebsocket/IXSetThreadName.cpp.s

ixwebsocket/IXSocket.o: ixwebsocket/IXSocket.cpp.o

.PHONY : ixwebsocket/IXSocket.o

# target to build an object file
ixwebsocket/IXSocket.cpp.o:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXSocket.cpp.o
.PHONY : ixwebsocket/IXSocket.cpp.o

ixwebsocket/IXSocket.i: ixwebsocket/IXSocket.cpp.i

.PHONY : ixwebsocket/IXSocket.i

# target to preprocess a source file
ixwebsocket/IXSocket.cpp.i:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXSocket.cpp.i
.PHONY : ixwebsocket/IXSocket.cpp.i

ixwebsocket/IXSocket.s: ixwebsocket/IXSocket.cpp.s

.PHONY : ixwebsocket/IXSocket.s

# target to generate assembly for a file
ixwebsocket/IXSocket.cpp.s:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXSocket.cpp.s
.PHONY : ixwebsocket/IXSocket.cpp.s

ixwebsocket/IXSocketConnect.o: ixwebsocket/IXSocketConnect.cpp.o

.PHONY : ixwebsocket/IXSocketConnect.o

# target to build an object file
ixwebsocket/IXSocketConnect.cpp.o:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXSocketConnect.cpp.o
.PHONY : ixwebsocket/IXSocketConnect.cpp.o

ixwebsocket/IXSocketConnect.i: ixwebsocket/IXSocketConnect.cpp.i

.PHONY : ixwebsocket/IXSocketConnect.i

# target to preprocess a source file
ixwebsocket/IXSocketConnect.cpp.i:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXSocketConnect.cpp.i
.PHONY : ixwebsocket/IXSocketConnect.cpp.i

ixwebsocket/IXSocketConnect.s: ixwebsocket/IXSocketConnect.cpp.s

.PHONY : ixwebsocket/IXSocketConnect.s

# target to generate assembly for a file
ixwebsocket/IXSocketConnect.cpp.s:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXSocketConnect.cpp.s
.PHONY : ixwebsocket/IXSocketConnect.cpp.s

ixwebsocket/IXSocketFactory.o: ixwebsocket/IXSocketFactory.cpp.o

.PHONY : ixwebsocket/IXSocketFactory.o

# target to build an object file
ixwebsocket/IXSocketFactory.cpp.o:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXSocketFactory.cpp.o
.PHONY : ixwebsocket/IXSocketFactory.cpp.o

ixwebsocket/IXSocketFactory.i: ixwebsocket/IXSocketFactory.cpp.i

.PHONY : ixwebsocket/IXSocketFactory.i

# target to preprocess a source file
ixwebsocket/IXSocketFactory.cpp.i:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXSocketFactory.cpp.i
.PHONY : ixwebsocket/IXSocketFactory.cpp.i

ixwebsocket/IXSocketFactory.s: ixwebsocket/IXSocketFactory.cpp.s

.PHONY : ixwebsocket/IXSocketFactory.s

# target to generate assembly for a file
ixwebsocket/IXSocketFactory.cpp.s:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXSocketFactory.cpp.s
.PHONY : ixwebsocket/IXSocketFactory.cpp.s

ixwebsocket/IXSocketOpenSSL.o: ixwebsocket/IXSocketOpenSSL.cpp.o

.PHONY : ixwebsocket/IXSocketOpenSSL.o

# target to build an object file
ixwebsocket/IXSocketOpenSSL.cpp.o:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXSocketOpenSSL.cpp.o
.PHONY : ixwebsocket/IXSocketOpenSSL.cpp.o

ixwebsocket/IXSocketOpenSSL.i: ixwebsocket/IXSocketOpenSSL.cpp.i

.PHONY : ixwebsocket/IXSocketOpenSSL.i

# target to preprocess a source file
ixwebsocket/IXSocketOpenSSL.cpp.i:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXSocketOpenSSL.cpp.i
.PHONY : ixwebsocket/IXSocketOpenSSL.cpp.i

ixwebsocket/IXSocketOpenSSL.s: ixwebsocket/IXSocketOpenSSL.cpp.s

.PHONY : ixwebsocket/IXSocketOpenSSL.s

# target to generate assembly for a file
ixwebsocket/IXSocketOpenSSL.cpp.s:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXSocketOpenSSL.cpp.s
.PHONY : ixwebsocket/IXSocketOpenSSL.cpp.s

ixwebsocket/IXSocketServer.o: ixwebsocket/IXSocketServer.cpp.o

.PHONY : ixwebsocket/IXSocketServer.o

# target to build an object file
ixwebsocket/IXSocketServer.cpp.o:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXSocketServer.cpp.o
.PHONY : ixwebsocket/IXSocketServer.cpp.o

ixwebsocket/IXSocketServer.i: ixwebsocket/IXSocketServer.cpp.i

.PHONY : ixwebsocket/IXSocketServer.i

# target to preprocess a source file
ixwebsocket/IXSocketServer.cpp.i:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXSocketServer.cpp.i
.PHONY : ixwebsocket/IXSocketServer.cpp.i

ixwebsocket/IXSocketServer.s: ixwebsocket/IXSocketServer.cpp.s

.PHONY : ixwebsocket/IXSocketServer.s

# target to generate assembly for a file
ixwebsocket/IXSocketServer.cpp.s:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXSocketServer.cpp.s
.PHONY : ixwebsocket/IXSocketServer.cpp.s

ixwebsocket/IXSocketTLSOptions.o: ixwebsocket/IXSocketTLSOptions.cpp.o

.PHONY : ixwebsocket/IXSocketTLSOptions.o

# target to build an object file
ixwebsocket/IXSocketTLSOptions.cpp.o:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXSocketTLSOptions.cpp.o
.PHONY : ixwebsocket/IXSocketTLSOptions.cpp.o

ixwebsocket/IXSocketTLSOptions.i: ixwebsocket/IXSocketTLSOptions.cpp.i

.PHONY : ixwebsocket/IXSocketTLSOptions.i

# target to preprocess a source file
ixwebsocket/IXSocketTLSOptions.cpp.i:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXSocketTLSOptions.cpp.i
.PHONY : ixwebsocket/IXSocketTLSOptions.cpp.i

ixwebsocket/IXSocketTLSOptions.s: ixwebsocket/IXSocketTLSOptions.cpp.s

.PHONY : ixwebsocket/IXSocketTLSOptions.s

# target to generate assembly for a file
ixwebsocket/IXSocketTLSOptions.cpp.s:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXSocketTLSOptions.cpp.s
.PHONY : ixwebsocket/IXSocketTLSOptions.cpp.s

ixwebsocket/IXStrCaseCompare.o: ixwebsocket/IXStrCaseCompare.cpp.o

.PHONY : ixwebsocket/IXStrCaseCompare.o

# target to build an object file
ixwebsocket/IXStrCaseCompare.cpp.o:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXStrCaseCompare.cpp.o
.PHONY : ixwebsocket/IXStrCaseCompare.cpp.o

ixwebsocket/IXStrCaseCompare.i: ixwebsocket/IXStrCaseCompare.cpp.i

.PHONY : ixwebsocket/IXStrCaseCompare.i

# target to preprocess a source file
ixwebsocket/IXStrCaseCompare.cpp.i:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXStrCaseCompare.cpp.i
.PHONY : ixwebsocket/IXStrCaseCompare.cpp.i

ixwebsocket/IXStrCaseCompare.s: ixwebsocket/IXStrCaseCompare.cpp.s

.PHONY : ixwebsocket/IXStrCaseCompare.s

# target to generate assembly for a file
ixwebsocket/IXStrCaseCompare.cpp.s:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXStrCaseCompare.cpp.s
.PHONY : ixwebsocket/IXStrCaseCompare.cpp.s

ixwebsocket/IXUdpSocket.o: ixwebsocket/IXUdpSocket.cpp.o

.PHONY : ixwebsocket/IXUdpSocket.o

# target to build an object file
ixwebsocket/IXUdpSocket.cpp.o:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXUdpSocket.cpp.o
.PHONY : ixwebsocket/IXUdpSocket.cpp.o

ixwebsocket/IXUdpSocket.i: ixwebsocket/IXUdpSocket.cpp.i

.PHONY : ixwebsocket/IXUdpSocket.i

# target to preprocess a source file
ixwebsocket/IXUdpSocket.cpp.i:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXUdpSocket.cpp.i
.PHONY : ixwebsocket/IXUdpSocket.cpp.i

ixwebsocket/IXUdpSocket.s: ixwebsocket/IXUdpSocket.cpp.s

.PHONY : ixwebsocket/IXUdpSocket.s

# target to generate assembly for a file
ixwebsocket/IXUdpSocket.cpp.s:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXUdpSocket.cpp.s
.PHONY : ixwebsocket/IXUdpSocket.cpp.s

ixwebsocket/IXUrlParser.o: ixwebsocket/IXUrlParser.cpp.o

.PHONY : ixwebsocket/IXUrlParser.o

# target to build an object file
ixwebsocket/IXUrlParser.cpp.o:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXUrlParser.cpp.o
.PHONY : ixwebsocket/IXUrlParser.cpp.o

ixwebsocket/IXUrlParser.i: ixwebsocket/IXUrlParser.cpp.i

.PHONY : ixwebsocket/IXUrlParser.i

# target to preprocess a source file
ixwebsocket/IXUrlParser.cpp.i:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXUrlParser.cpp.i
.PHONY : ixwebsocket/IXUrlParser.cpp.i

ixwebsocket/IXUrlParser.s: ixwebsocket/IXUrlParser.cpp.s

.PHONY : ixwebsocket/IXUrlParser.s

# target to generate assembly for a file
ixwebsocket/IXUrlParser.cpp.s:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXUrlParser.cpp.s
.PHONY : ixwebsocket/IXUrlParser.cpp.s

ixwebsocket/IXUserAgent.o: ixwebsocket/IXUserAgent.cpp.o

.PHONY : ixwebsocket/IXUserAgent.o

# target to build an object file
ixwebsocket/IXUserAgent.cpp.o:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXUserAgent.cpp.o
.PHONY : ixwebsocket/IXUserAgent.cpp.o

ixwebsocket/IXUserAgent.i: ixwebsocket/IXUserAgent.cpp.i

.PHONY : ixwebsocket/IXUserAgent.i

# target to preprocess a source file
ixwebsocket/IXUserAgent.cpp.i:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXUserAgent.cpp.i
.PHONY : ixwebsocket/IXUserAgent.cpp.i

ixwebsocket/IXUserAgent.s: ixwebsocket/IXUserAgent.cpp.s

.PHONY : ixwebsocket/IXUserAgent.s

# target to generate assembly for a file
ixwebsocket/IXUserAgent.cpp.s:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXUserAgent.cpp.s
.PHONY : ixwebsocket/IXUserAgent.cpp.s

ixwebsocket/IXUuid.o: ixwebsocket/IXUuid.cpp.o

.PHONY : ixwebsocket/IXUuid.o

# target to build an object file
ixwebsocket/IXUuid.cpp.o:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXUuid.cpp.o
.PHONY : ixwebsocket/IXUuid.cpp.o

ixwebsocket/IXUuid.i: ixwebsocket/IXUuid.cpp.i

.PHONY : ixwebsocket/IXUuid.i

# target to preprocess a source file
ixwebsocket/IXUuid.cpp.i:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXUuid.cpp.i
.PHONY : ixwebsocket/IXUuid.cpp.i

ixwebsocket/IXUuid.s: ixwebsocket/IXUuid.cpp.s

.PHONY : ixwebsocket/IXUuid.s

# target to generate assembly for a file
ixwebsocket/IXUuid.cpp.s:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXUuid.cpp.s
.PHONY : ixwebsocket/IXUuid.cpp.s

ixwebsocket/IXWebSocket.o: ixwebsocket/IXWebSocket.cpp.o

.PHONY : ixwebsocket/IXWebSocket.o

# target to build an object file
ixwebsocket/IXWebSocket.cpp.o:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXWebSocket.cpp.o
.PHONY : ixwebsocket/IXWebSocket.cpp.o

ixwebsocket/IXWebSocket.i: ixwebsocket/IXWebSocket.cpp.i

.PHONY : ixwebsocket/IXWebSocket.i

# target to preprocess a source file
ixwebsocket/IXWebSocket.cpp.i:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXWebSocket.cpp.i
.PHONY : ixwebsocket/IXWebSocket.cpp.i

ixwebsocket/IXWebSocket.s: ixwebsocket/IXWebSocket.cpp.s

.PHONY : ixwebsocket/IXWebSocket.s

# target to generate assembly for a file
ixwebsocket/IXWebSocket.cpp.s:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXWebSocket.cpp.s
.PHONY : ixwebsocket/IXWebSocket.cpp.s

ixwebsocket/IXWebSocketCloseConstants.o: ixwebsocket/IXWebSocketCloseConstants.cpp.o

.PHONY : ixwebsocket/IXWebSocketCloseConstants.o

# target to build an object file
ixwebsocket/IXWebSocketCloseConstants.cpp.o:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXWebSocketCloseConstants.cpp.o
.PHONY : ixwebsocket/IXWebSocketCloseConstants.cpp.o

ixwebsocket/IXWebSocketCloseConstants.i: ixwebsocket/IXWebSocketCloseConstants.cpp.i

.PHONY : ixwebsocket/IXWebSocketCloseConstants.i

# target to preprocess a source file
ixwebsocket/IXWebSocketCloseConstants.cpp.i:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXWebSocketCloseConstants.cpp.i
.PHONY : ixwebsocket/IXWebSocketCloseConstants.cpp.i

ixwebsocket/IXWebSocketCloseConstants.s: ixwebsocket/IXWebSocketCloseConstants.cpp.s

.PHONY : ixwebsocket/IXWebSocketCloseConstants.s

# target to generate assembly for a file
ixwebsocket/IXWebSocketCloseConstants.cpp.s:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXWebSocketCloseConstants.cpp.s
.PHONY : ixwebsocket/IXWebSocketCloseConstants.cpp.s

ixwebsocket/IXWebSocketHandshake.o: ixwebsocket/IXWebSocketHandshake.cpp.o

.PHONY : ixwebsocket/IXWebSocketHandshake.o

# target to build an object file
ixwebsocket/IXWebSocketHandshake.cpp.o:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXWebSocketHandshake.cpp.o
.PHONY : ixwebsocket/IXWebSocketHandshake.cpp.o

ixwebsocket/IXWebSocketHandshake.i: ixwebsocket/IXWebSocketHandshake.cpp.i

.PHONY : ixwebsocket/IXWebSocketHandshake.i

# target to preprocess a source file
ixwebsocket/IXWebSocketHandshake.cpp.i:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXWebSocketHandshake.cpp.i
.PHONY : ixwebsocket/IXWebSocketHandshake.cpp.i

ixwebsocket/IXWebSocketHandshake.s: ixwebsocket/IXWebSocketHandshake.cpp.s

.PHONY : ixwebsocket/IXWebSocketHandshake.s

# target to generate assembly for a file
ixwebsocket/IXWebSocketHandshake.cpp.s:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXWebSocketHandshake.cpp.s
.PHONY : ixwebsocket/IXWebSocketHandshake.cpp.s

ixwebsocket/IXWebSocketHttpHeaders.o: ixwebsocket/IXWebSocketHttpHeaders.cpp.o

.PHONY : ixwebsocket/IXWebSocketHttpHeaders.o

# target to build an object file
ixwebsocket/IXWebSocketHttpHeaders.cpp.o:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXWebSocketHttpHeaders.cpp.o
.PHONY : ixwebsocket/IXWebSocketHttpHeaders.cpp.o

ixwebsocket/IXWebSocketHttpHeaders.i: ixwebsocket/IXWebSocketHttpHeaders.cpp.i

.PHONY : ixwebsocket/IXWebSocketHttpHeaders.i

# target to preprocess a source file
ixwebsocket/IXWebSocketHttpHeaders.cpp.i:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXWebSocketHttpHeaders.cpp.i
.PHONY : ixwebsocket/IXWebSocketHttpHeaders.cpp.i

ixwebsocket/IXWebSocketHttpHeaders.s: ixwebsocket/IXWebSocketHttpHeaders.cpp.s

.PHONY : ixwebsocket/IXWebSocketHttpHeaders.s

# target to generate assembly for a file
ixwebsocket/IXWebSocketHttpHeaders.cpp.s:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXWebSocketHttpHeaders.cpp.s
.PHONY : ixwebsocket/IXWebSocketHttpHeaders.cpp.s

ixwebsocket/IXWebSocketPerMessageDeflate.o: ixwebsocket/IXWebSocketPerMessageDeflate.cpp.o

.PHONY : ixwebsocket/IXWebSocketPerMessageDeflate.o

# target to build an object file
ixwebsocket/IXWebSocketPerMessageDeflate.cpp.o:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXWebSocketPerMessageDeflate.cpp.o
.PHONY : ixwebsocket/IXWebSocketPerMessageDeflate.cpp.o

ixwebsocket/IXWebSocketPerMessageDeflate.i: ixwebsocket/IXWebSocketPerMessageDeflate.cpp.i

.PHONY : ixwebsocket/IXWebSocketPerMessageDeflate.i

# target to preprocess a source file
ixwebsocket/IXWebSocketPerMessageDeflate.cpp.i:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXWebSocketPerMessageDeflate.cpp.i
.PHONY : ixwebsocket/IXWebSocketPerMessageDeflate.cpp.i

ixwebsocket/IXWebSocketPerMessageDeflate.s: ixwebsocket/IXWebSocketPerMessageDeflate.cpp.s

.PHONY : ixwebsocket/IXWebSocketPerMessageDeflate.s

# target to generate assembly for a file
ixwebsocket/IXWebSocketPerMessageDeflate.cpp.s:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXWebSocketPerMessageDeflate.cpp.s
.PHONY : ixwebsocket/IXWebSocketPerMessageDeflate.cpp.s

ixwebsocket/IXWebSocketPerMessageDeflateCodec.o: ixwebsocket/IXWebSocketPerMessageDeflateCodec.cpp.o

.PHONY : ixwebsocket/IXWebSocketPerMessageDeflateCodec.o

# target to build an object file
ixwebsocket/IXWebSocketPerMessageDeflateCodec.cpp.o:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXWebSocketPerMessageDeflateCodec.cpp.o
.PHONY : ixwebsocket/IXWebSocketPerMessageDeflateCodec.cpp.o

ixwebsocket/IXWebSocketPerMessageDeflateCodec.i: ixwebsocket/IXWebSocketPerMessageDeflateCodec.cpp.i

.PHONY : ixwebsocket/IXWebSocketPerMessageDeflateCodec.i

# target to preprocess a source file
ixwebsocket/IXWebSocketPerMessageDeflateCodec.cpp.i:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXWebSocketPerMessageDeflateCodec.cpp.i
.PHONY : ixwebsocket/IXWebSocketPerMessageDeflateCodec.cpp.i

ixwebsocket/IXWebSocketPerMessageDeflateCodec.s: ixwebsocket/IXWebSocketPerMessageDeflateCodec.cpp.s

.PHONY : ixwebsocket/IXWebSocketPerMessageDeflateCodec.s

# target to generate assembly for a file
ixwebsocket/IXWebSocketPerMessageDeflateCodec.cpp.s:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXWebSocketPerMessageDeflateCodec.cpp.s
.PHONY : ixwebsocket/IXWebSocketPerMessageDeflateCodec.cpp.s

ixwebsocket/IXWebSocketPerMessageDeflateOptions.o: ixwebsocket/IXWebSocketPerMessageDeflateOptions.cpp.o

.PHONY : ixwebsocket/IXWebSocketPerMessageDeflateOptions.o

# target to build an object file
ixwebsocket/IXWebSocketPerMessageDeflateOptions.cpp.o:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXWebSocketPerMessageDeflateOptions.cpp.o
.PHONY : ixwebsocket/IXWebSocketPerMessageDeflateOptions.cpp.o

ixwebsocket/IXWebSocketPerMessageDeflateOptions.i: ixwebsocket/IXWebSocketPerMessageDeflateOptions.cpp.i

.PHONY : ixwebsocket/IXWebSocketPerMessageDeflateOptions.i

# target to preprocess a source file
ixwebsocket/IXWebSocketPerMessageDeflateOptions.cpp.i:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXWebSocketPerMessageDeflateOptions.cpp.i
.PHONY : ixwebsocket/IXWebSocketPerMessageDeflateOptions.cpp.i

ixwebsocket/IXWebSocketPerMessageDeflateOptions.s: ixwebsocket/IXWebSocketPerMessageDeflateOptions.cpp.s

.PHONY : ixwebsocket/IXWebSocketPerMessageDeflateOptions.s

# target to generate assembly for a file
ixwebsocket/IXWebSocketPerMessageDeflateOptions.cpp.s:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXWebSocketPerMessageDeflateOptions.cpp.s
.PHONY : ixwebsocket/IXWebSocketPerMessageDeflateOptions.cpp.s

ixwebsocket/IXWebSocketProxyServer.o: ixwebsocket/IXWebSocketProxyServer.cpp.o

.PHONY : ixwebsocket/IXWebSocketProxyServer.o

# target to build an object file
ixwebsocket/IXWebSocketProxyServer.cpp.o:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXWebSocketProxyServer.cpp.o
.PHONY : ixwebsocket/IXWebSocketProxyServer.cpp.o

ixwebsocket/IXWebSocketProxyServer.i: ixwebsocket/IXWebSocketProxyServer.cpp.i

.PHONY : ixwebsocket/IXWebSocketProxyServer.i

# target to preprocess a source file
ixwebsocket/IXWebSocketProxyServer.cpp.i:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXWebSocketProxyServer.cpp.i
.PHONY : ixwebsocket/IXWebSocketProxyServer.cpp.i

ixwebsocket/IXWebSocketProxyServer.s: ixwebsocket/IXWebSocketProxyServer.cpp.s

.PHONY : ixwebsocket/IXWebSocketProxyServer.s

# target to generate assembly for a file
ixwebsocket/IXWebSocketProxyServer.cpp.s:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXWebSocketProxyServer.cpp.s
.PHONY : ixwebsocket/IXWebSocketProxyServer.cpp.s

ixwebsocket/IXWebSocketServer.o: ixwebsocket/IXWebSocketServer.cpp.o

.PHONY : ixwebsocket/IXWebSocketServer.o

# target to build an object file
ixwebsocket/IXWebSocketServer.cpp.o:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXWebSocketServer.cpp.o
.PHONY : ixwebsocket/IXWebSocketServer.cpp.o

ixwebsocket/IXWebSocketServer.i: ixwebsocket/IXWebSocketServer.cpp.i

.PHONY : ixwebsocket/IXWebSocketServer.i

# target to preprocess a source file
ixwebsocket/IXWebSocketServer.cpp.i:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXWebSocketServer.cpp.i
.PHONY : ixwebsocket/IXWebSocketServer.cpp.i

ixwebsocket/IXWebSocketServer.s: ixwebsocket/IXWebSocketServer.cpp.s

.PHONY : ixwebsocket/IXWebSocketServer.s

# target to generate assembly for a file
ixwebsocket/IXWebSocketServer.cpp.s:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXWebSocketServer.cpp.s
.PHONY : ixwebsocket/IXWebSocketServer.cpp.s

ixwebsocket/IXWebSocketTransport.o: ixwebsocket/IXWebSocketTransport.cpp.o

.PHONY : ixwebsocket/IXWebSocketTransport.o

# target to build an object file
ixwebsocket/IXWebSocketTransport.cpp.o:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXWebSocketTransport.cpp.o
.PHONY : ixwebsocket/IXWebSocketTransport.cpp.o

ixwebsocket/IXWebSocketTransport.i: ixwebsocket/IXWebSocketTransport.cpp.i

.PHONY : ixwebsocket/IXWebSocketTransport.i

# target to preprocess a source file
ixwebsocket/IXWebSocketTransport.cpp.i:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXWebSocketTransport.cpp.i
.PHONY : ixwebsocket/IXWebSocketTransport.cpp.i

ixwebsocket/IXWebSocketTransport.s: ixwebsocket/IXWebSocketTransport.cpp.s

.PHONY : ixwebsocket/IXWebSocketTransport.s

# target to generate assembly for a file
ixwebsocket/IXWebSocketTransport.cpp.s:
	$(MAKE) -f CMakeFiles/ixwebsocket.dir/build.make CMakeFiles/ixwebsocket.dir/ixwebsocket/IXWebSocketTransport.cpp.s
.PHONY : ixwebsocket/IXWebSocketTransport.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/demo.dir/build.make CMakeFiles/demo.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... install/local"
	@echo "... demo"
	@echo "... ixwebsocket"
	@echo "... ixwebsocket/IXBench.o"
	@echo "... ixwebsocket/IXBench.i"
	@echo "... ixwebsocket/IXBench.s"
	@echo "... ixwebsocket/IXCancellationRequest.o"
	@echo "... ixwebsocket/IXCancellationRequest.i"
	@echo "... ixwebsocket/IXCancellationRequest.s"
	@echo "... ixwebsocket/IXConnectionState.o"
	@echo "... ixwebsocket/IXConnectionState.i"
	@echo "... ixwebsocket/IXConnectionState.s"
	@echo "... ixwebsocket/IXDNSLookup.o"
	@echo "... ixwebsocket/IXDNSLookup.i"
	@echo "... ixwebsocket/IXDNSLookup.s"
	@echo "... ixwebsocket/IXExponentialBackoff.o"
	@echo "... ixwebsocket/IXExponentialBackoff.i"
	@echo "... ixwebsocket/IXExponentialBackoff.s"
	@echo "... ixwebsocket/IXGetFreePort.o"
	@echo "... ixwebsocket/IXGetFreePort.i"
	@echo "... ixwebsocket/IXGetFreePort.s"
	@echo "... ixwebsocket/IXGzipCodec.o"
	@echo "... ixwebsocket/IXGzipCodec.i"
	@echo "... ixwebsocket/IXGzipCodec.s"
	@echo "... ixwebsocket/IXHttp.o"
	@echo "... ixwebsocket/IXHttp.i"
	@echo "... ixwebsocket/IXHttp.s"
	@echo "... ixwebsocket/IXHttpClient.o"
	@echo "... ixwebsocket/IXHttpClient.i"
	@echo "... ixwebsocket/IXHttpClient.s"
	@echo "... ixwebsocket/IXHttpServer.o"
	@echo "... ixwebsocket/IXHttpServer.i"
	@echo "... ixwebsocket/IXHttpServer.s"
	@echo "... ixwebsocket/IXNetSystem.o"
	@echo "... ixwebsocket/IXNetSystem.i"
	@echo "... ixwebsocket/IXNetSystem.s"
	@echo "... ixwebsocket/IXSelectInterrupt.o"
	@echo "... ixwebsocket/IXSelectInterrupt.i"
	@echo "... ixwebsocket/IXSelectInterrupt.s"
	@echo "... ixwebsocket/IXSelectInterruptEvent.o"
	@echo "... ixwebsocket/IXSelectInterruptEvent.i"
	@echo "... ixwebsocket/IXSelectInterruptEvent.s"
	@echo "... ixwebsocket/IXSelectInterruptFactory.o"
	@echo "... ixwebsocket/IXSelectInterruptFactory.i"
	@echo "... ixwebsocket/IXSelectInterruptFactory.s"
	@echo "... ixwebsocket/IXSelectInterruptPipe.o"
	@echo "... ixwebsocket/IXSelectInterruptPipe.i"
	@echo "... ixwebsocket/IXSelectInterruptPipe.s"
	@echo "... ixwebsocket/IXSetThreadName.o"
	@echo "... ixwebsocket/IXSetThreadName.i"
	@echo "... ixwebsocket/IXSetThreadName.s"
	@echo "... ixwebsocket/IXSocket.o"
	@echo "... ixwebsocket/IXSocket.i"
	@echo "... ixwebsocket/IXSocket.s"
	@echo "... ixwebsocket/IXSocketConnect.o"
	@echo "... ixwebsocket/IXSocketConnect.i"
	@echo "... ixwebsocket/IXSocketConnect.s"
	@echo "... ixwebsocket/IXSocketFactory.o"
	@echo "... ixwebsocket/IXSocketFactory.i"
	@echo "... ixwebsocket/IXSocketFactory.s"
	@echo "... ixwebsocket/IXSocketOpenSSL.o"
	@echo "... ixwebsocket/IXSocketOpenSSL.i"
	@echo "... ixwebsocket/IXSocketOpenSSL.s"
	@echo "... ixwebsocket/IXSocketServer.o"
	@echo "... ixwebsocket/IXSocketServer.i"
	@echo "... ixwebsocket/IXSocketServer.s"
	@echo "... ixwebsocket/IXSocketTLSOptions.o"
	@echo "... ixwebsocket/IXSocketTLSOptions.i"
	@echo "... ixwebsocket/IXSocketTLSOptions.s"
	@echo "... ixwebsocket/IXStrCaseCompare.o"
	@echo "... ixwebsocket/IXStrCaseCompare.i"
	@echo "... ixwebsocket/IXStrCaseCompare.s"
	@echo "... ixwebsocket/IXUdpSocket.o"
	@echo "... ixwebsocket/IXUdpSocket.i"
	@echo "... ixwebsocket/IXUdpSocket.s"
	@echo "... ixwebsocket/IXUrlParser.o"
	@echo "... ixwebsocket/IXUrlParser.i"
	@echo "... ixwebsocket/IXUrlParser.s"
	@echo "... ixwebsocket/IXUserAgent.o"
	@echo "... ixwebsocket/IXUserAgent.i"
	@echo "... ixwebsocket/IXUserAgent.s"
	@echo "... ixwebsocket/IXUuid.o"
	@echo "... ixwebsocket/IXUuid.i"
	@echo "... ixwebsocket/IXUuid.s"
	@echo "... ixwebsocket/IXWebSocket.o"
	@echo "... ixwebsocket/IXWebSocket.i"
	@echo "... ixwebsocket/IXWebSocket.s"
	@echo "... ixwebsocket/IXWebSocketCloseConstants.o"
	@echo "... ixwebsocket/IXWebSocketCloseConstants.i"
	@echo "... ixwebsocket/IXWebSocketCloseConstants.s"
	@echo "... ixwebsocket/IXWebSocketHandshake.o"
	@echo "... ixwebsocket/IXWebSocketHandshake.i"
	@echo "... ixwebsocket/IXWebSocketHandshake.s"
	@echo "... ixwebsocket/IXWebSocketHttpHeaders.o"
	@echo "... ixwebsocket/IXWebSocketHttpHeaders.i"
	@echo "... ixwebsocket/IXWebSocketHttpHeaders.s"
	@echo "... ixwebsocket/IXWebSocketPerMessageDeflate.o"
	@echo "... ixwebsocket/IXWebSocketPerMessageDeflate.i"
	@echo "... ixwebsocket/IXWebSocketPerMessageDeflate.s"
	@echo "... ixwebsocket/IXWebSocketPerMessageDeflateCodec.o"
	@echo "... ixwebsocket/IXWebSocketPerMessageDeflateCodec.i"
	@echo "... ixwebsocket/IXWebSocketPerMessageDeflateCodec.s"
	@echo "... ixwebsocket/IXWebSocketPerMessageDeflateOptions.o"
	@echo "... ixwebsocket/IXWebSocketPerMessageDeflateOptions.i"
	@echo "... ixwebsocket/IXWebSocketPerMessageDeflateOptions.s"
	@echo "... ixwebsocket/IXWebSocketProxyServer.o"
	@echo "... ixwebsocket/IXWebSocketProxyServer.i"
	@echo "... ixwebsocket/IXWebSocketProxyServer.s"
	@echo "... ixwebsocket/IXWebSocketServer.o"
	@echo "... ixwebsocket/IXWebSocketServer.i"
	@echo "... ixwebsocket/IXWebSocketServer.s"
	@echo "... ixwebsocket/IXWebSocketTransport.o"
	@echo "... ixwebsocket/IXWebSocketTransport.i"
	@echo "... ixwebsocket/IXWebSocketTransport.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

