FROM debian:stretch

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update 
RUN apt-get -y install g++ 
RUN apt-get -y install libssl-dev
RUN apt-get -y install gdb
RUN apt-get -y install screen
RUN apt-get -y install procps
RUN apt-get -y install lsof
RUN apt-get -y install libz-dev
RUN apt-get -y install vim
RUN apt-get -y install make
RUN apt-get -y install cmake

COPY . .

WORKDIR test
RUN ["sh", "build_linux.sh"]
