FROM debian:stretch

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update 
RUN apt-get -y install g++ 
RUN apt-get -y install libssl-dev
RUN apt-get -y install gdb
RUN apt-get -y install screen
RUN apt-get -y install procps
RUN apt-get -y install lsof
RUN apt-get -y install libz-dev
RUN apt-get -y install vim

COPY . .

WORKDIR examples/ws_connect
RUN ["sh", "build_linux.sh"]
