# Build time
FROM ubuntu:groovy as build

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update

RUN apt-get -y install g++ libssl-dev libz-dev make python ninja-build
RUN apt-get -y install cmake

COPY . /opt
WORKDIR /opt

RUN ["make", "test"]
